[[item]]
file = "~/.config/awesome/config/flavours.lua"
template = "lua"
subtemplate = "default"
rewrite = true

[[item]]
file = "~/.config/nvim/lua/theme/colours.lua"
template = "lua"
subtemplate = "default"
rewrite = true

[[item]]
file = "~/.config/wezterm/flavours.lua"
template = "lua"
subtemplate = "default"
rewrite = true

[[item]]
file = "~/.config/qutebrowser/flavours.py"
template = "qutebrowser"
subtemplate = "default"
rewrite = true

[[item]]
file = "~/.config/rofi/colours.rasi"
template = "rofi"
subtemplate = "custom"
rewrite = true

[[item]]
file = "~/.local/share/localweb/startpage/style/style.css"
template = "startpage"
subtemplate = "style"
start = "  /* start flavours */"
end = "  /* end flavours */"

[[item]]
file = "~/.local/share/localweb/startpage/script/script.js"
template = "startpage"
subtemplate = "script"
start = "// Start flavours"
end = "// End flavours"

[[item]]
file = "~/.config/X11/xresources"
template = "xresources"
subtemplate = "custom"
start = "! Start flavours"
end = "! End flavours"
